## Préambule
site_name: mon_site
site_description: 2nd website
site_author: Raj
repo_name: gitlab
site_favicon: favicon.ico

theme: 
  name: readthedocs # mkdocs 

## Architecture
nav:
  - Accueil: index.md
  - Guide:
    - Pense-bête: pense_bete.md

## Extensions
